services:
  db:
    image: postgres:13-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_NAME: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
    restart: always
    env_file:
      - .env
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
#    command: ['fastapi', 'run', 'main.py', '--host', '0.0.0.0', '--port', '8000']
    command: sh -c `fastapi run main.py --host 0.0.0.0 --port 8000`
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    volumes:
      - /Users/macbook/PycharmProjects/WebSocketChat/migration:/app/migration

