"""move read field

Revision ID: 1e1b5db8b939
Revises: 8658cb5922d9
Create Date: 2025-03-13 23:34:26.036154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e1b5db8b939'
down_revision: Union[str, None] = '8658cb5922d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('read', sa.Boolean(), nullable=True))
    op.drop_column('user_message_table', 'read')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_message_table', sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'read')
    # ### end Alembic commands ###
