"""fix

Revision ID: 3418b88d6cc5
Revises: 1e1b5db8b939
Create Date: 2025-03-14 05:41:30.965831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3418b88d6cc5'
down_revision: Union[str, None] = '1e1b5db8b939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_message_table', sa.Column('read', sa.Boolean(), server_default='False', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_message_table', 'read')
    # ### end Alembic commands ###
