"""add joined loading for groups

Revision ID: 3d301e95adcc
Revises: 418d90b62b21
Create Date: 2025-03-13 20:57:29.882171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d301e95adcc'
down_revision: Union[str, None] = '418d90b62b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_group_table',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.drop_table('association_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_table',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='association_table_group_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='association_table_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'group_id', name='association_table_pkey')
    )
    op.drop_table('user_group_table')
    # ### end Alembic commands ###
